-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID,COUNT(CAR_ID)	AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
AND CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
        GROUP BY CAR_ID
        HAVING COUNT(CAR_ID) >= 5
    )

GROUP BY CAR_ID, MONTH
ORDER BY MONTH ASC, CAR_ID DESC ;



# GROUP BY CAR_ID 로 할 경우 문제점 
# SELECT 시에 어떤 월로 표현할지 부정확하게됨  
# MONTH (월)	CAR_ID (자동차 번호)	COUNT (대여 횟수)
# 8? 9? 10?	1	3

# GROUP BY CAR_ID, MONTH
# 특정 월에만 5번이상 차를 찾게됨(목표-> 전체기간동안 5번이상 빌린차 찾기)
# 서브쿼리로 해결 