-- 코드를 작성해주세요
SELECT 
SUM(G.SCORE) AS SCORE,	E.EMP_NO,	E.EMP_NAME,	E.POSITION,	E.EMAIL
FROM HR_EMPLOYEES AS E
JOIN HR_GRADE AS G
ON E.EMP_NO = G.EMP_NO
WHERE G.YEAR = 2022
GROUP BY E.EMP_NO
ORDER BY SCORE DESC            
LIMIT 1;

# EMP_NO, YEAR 기준 상하반기 점수합 -> 사번과 연결 -> 순위 매김 MAX 출 력