-- 코드를 입력하세요
SELECT I.NAME,	I.DATETIME
FROM ANIMAL_INS AS I
LEFT JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NULL 
ORDER BY   I.DATETIME ASC 
LIMIT 3 ;


# 입양 못간 동물 -> 보호는 됐는데 입양기록에는 없는 동물 
# LEFTJOIN 
