-- 코드를 입력하세요
SELECT CAR_ID,  	
CASE
WHEN CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
    )
    THEN '대여중'
    ELSE '대여 가능'
END AS AVAILABILITY

FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC ;

# 해당 행 다 더해서 하나라도 해당 날짜의 대여중이면 최종 대여중으로 출력 