-- 코드를 작성해주세요
SELECT 
    CHILD.ID, 
    CHILD.GENOTYPE, 
    PARENT.GENOTYPE AS PARENT_GENOTYPE
FROM 
    ECOLI_DATA AS CHILD
JOIN 
    ECOLI_DATA AS PARENT 
    ON CHILD.PARENT_ID = PARENT.ID
WHERE 
    (CHILD.GENOTYPE & PARENT.GENOTYPE) = PARENT.GENOTYPE
# 자식비트자리에 부모비트자리 있는지 유무확인 
ORDER BY 
    CHILD.ID ASC;
