-- 코드를 작성해주세요
SELECT I.ITEM_ID,	I.ITEM_NAME,	I.RARITY
FROM ITEM_INFO AS I
JOIN ITEM_TREE AS T
ON I.ITEM_ID = T.ITEM_ID
WHERE I.ITEM_ID NOT IN (
SELECT PARENT_ITEM_ID
FROM ITEM_TREE 
WHERE PARENT_ITEM_ID IS NOT NULL # NOT IN 연산자 NULL값 존재시 모든행 UNKNOWN 반환됨
)
ORDER BY ITEM_ID DESC ;